version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        environment:
            APP_ENV: production
            APP_KEY: base64:YOUR_APP_KEY
            APP_DEBUG: false
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
        volumes:
            - .:/var/www/html
